# Ex5A NumPy Fundamentals

##  Practice importing the NumPy library and using it to work with arrays and basic numerical operations.


In [5]:
import numpy as np

## Array Basics

In [8]:
fruits = ['apple', 'banana', 'cherry', 'date']

print(fruits)

['apple', 'banana', 'cherry', 'date']


In [9]:
arr_1 = np.array(fruits)

print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [10]:
print(arr_1.dtype)
# U = Unicode string (text)
# 6 = maximum string length is 6 characters

<U6


In [11]:
arr_2 = np.array([
    [10, 11, 12],
    [13, 14, 15]
])

print(arr_2)

[[10 11 12]
 [13 14 15]]


In [12]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [14]:
print(arr_2)

# No, arr_2 is not permanently changed.

[[10 11 12]
 [13 14 15]]


In [15]:
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

print(arr_3)

[[1 3 5]
 [2 4 6]]


In [16]:
arr_4 = np.array([
    arr_3[0, 2],
    arr_3[1, 1]
])

print(arr_4)

[5 4]


In [17]:
arr_5 = np.ones((2, 2, 2))

print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
