# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

 ## Looping Through Arrays

In [3]:
arrA = np.array([[11, 12, 13],
                 [14, 15, 16]])

print(arrA)

[[11 12 13]
 [14 15 16]]


In [4]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [5]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


## The first loop goes through each row and multiplying by 2 doubles the entire row.
## The second loop goes through each indiduval number and multiplying by 2 will print each value.

In [6]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


# The result is different because x represents the whole row. 

## Joining and Stacking Arrays

In [8]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)

print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [9]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)

print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [10]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))

print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [11]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

print(stacked_array_2)
#  joined_array_1 and joined_array_2 have different shapes

ValueError: all input arrays must have the same shape

In [12]:
another_joined_array = np.concatenate((joined_array_1, arrA))

print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [13]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)

print(another_2)
# the arrays do not have the same number of rows

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [14]:
h_stack = np.hstack((arrA, arrA))  # hstack stacks arrays horizontally, side by side, adding more columns.

v_stack = np.vstack((arrA, arrA))  # vstack stacks arrays vertically, top to bottom, adding more rows.

d_stack = np.dstack((arrA, arrA))  # dstack stacks arrays by depth, creating a third dimension.

print(h_stack)
print(v_stack)
print(d_stack)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


 ## Splitting Arrays

In [16]:
splitsky = np.array_split(joined_array_1, 2)

print(splitsky)
#  It was split into 2 separate arrays and 2-dimensional arra. 

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [18]:
spliterino = np.array_split(joined_array_1, 3)

print(spliterino)
# It's 3 separate arrays,and 2-dimensional arra but uneven number of rows because only 3 groups. 

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [19]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')

print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Array

In [20]:
arrB = np.array([
    [7, 6],
    [13, 5],
    [7, 3]
])

arrB_sorted = np.sort(arrB)

print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [21]:
print(arrB)

z = arrB < 7

arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [22]:
y = arrB >= 7

arrD = arrB[y]

print(arrD)

[ 7 13  7]
