# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 21, size=2)

print(r_1)

[10  3]


In [3]:
r_2 = np.random.randint(1, 21, size=(1, 2))

print(r_2)

[[17  6]]


In [4]:
r_3 = np.random.rand(2, 1)

print(r_3)

[[0.88998856]
 [0.54496744]]


In [5]:
r_4 = np.random.randint(20, 101, size=(4, 5))

print(r_4)

[[ 31  87  69  49  48]
 [ 59  65  76 100  57]
 [ 57  86  79  22  81]
 [ 46  91  63  65  53]]


In [6]:
r_5 = np.random.rand(4, 5)

print(r_5)

[[0.31023437 0.77318495 0.55613754 0.04690347 0.76662978]
 [0.7659065  0.40090928 0.18928813 0.13018447 0.01590646]
 [0.36745738 0.44579327 0.03101318 0.52940574 0.66905835]
 [0.00937406 0.242219   0.33036214 0.868636   0.96536729]]


## Generating Random Choices from an Array

In [7]:
students = np.array([
    "Alex", "Maria", "Jordan", "Sophia",
    "Chris", "Emma", "Daniel", "Olivia",
    "James", "Mia", "Noah", "Ava"
])

print(students)

['Alex' 'Maria' 'Jordan' 'Sophia' 'Chris' 'Emma' 'Daniel' 'Olivia' 'James'
 'Mia' 'Noah' 'Ava']


In [8]:
call_on = np.random.choice(students)

print(call_on)

Maria


In [10]:
breakout_groups = np.random.choice(students, size=(3, 4))

print(breakout_groups)


[['Noah' 'Alex' 'Ava' 'Jordan']
 ['Alex' 'James' 'Jordan' 'James']
 ['James' 'Daniel' 'Jordan' 'Sophia']]


In [12]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.10, 0.10, 0.05,
       0.05, 0.10, 0.10, 0.05,
       0.05, 0.05, 0.05, 0.00]
)
print(call_on_weighted)

['Mia' 'Mia' 'Olivia' 'Olivia' 'Alex']


## Generating a Normal Distribution

In [13]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))

print(bell_curve)

[[ 1.23234646  9.42048242  0.24220628 12.10111117 17.38382897]
 [ 9.6927455  21.85251306 13.63882428 10.44339606  7.93749194]
 [ 2.78576586 19.01746215 10.30035712  7.23481758  9.78044289]
 [11.52199562 13.11405771  9.22034303 11.89475012  8.75304416]]
