# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.rand(4, 5)

print(r_1)
print(r_2)
print(r_3)
print(r_4)
print(r_5)

[12  3]
[[15  2]]
[[0.72032341]
 [0.50500735]]
[[ 56  81  72  63  38]
 [ 54  46  47  39  58]
 [ 93  27  48  77 100]
 [ 89  83  31  83  49]]
[[0.25993247 0.67590348 0.51325064 0.66693028 0.82241774]
 [0.69941945 0.93011805 0.07044982 0.58680286 0.81057166]
 [0.85930835 0.8489354  0.7731762  0.57926856 0.50541466]
 [0.249216   0.17046691 0.95695138 0.85601114 0.35536136]]


## Permutations

In [3]:
print(r_4)

[[ 56  81  72  63  38]
 [ 54  46  47  39  58]
 [ 93  27  48  77 100]
 [ 89  83  31  83  49]]


In [4]:
np.random.shuffle(r_4)

print(r_4)

[[ 89  83  31  83  49]
 [ 54  46  47  39  58]
 [ 93  27  48  77 100]
 [ 56  81  72  63  38]]


# I would use shuffle when I want to change the original array.I would use permutation when I want a shuffled copy but keep the original array.

## Mathematical Operations

In [7]:
print("r_1:")
print(r_1)
print("Shape of r_1:", r_1.shape)

print("r_2:")
print(r_2)
print("Shape of r_2:", r_2.shape)

result = np.add(r_1, r_2)

print(result)
print("Shape of result:", result.shape)

r_1:
[12  3]
Shape of r_1: (2,)
r_2:
[[15  2]]
Shape of r_2: (1, 2)
[[27  5]]
Shape of result: (1, 2)


In [8]:
print("r_1:")
print(r_1)
print("Shape of r_1:", r_1.shape)

print("r_3:")
print(r_3)
print("Shape of r_3:", r_3.shape)

result = np.add(r_1, r_3)

print(result)
print("Shape of result:", result.shape)

r_1:
[12  3]
Shape of r_1: (2,)
r_3:
[[0.72032341]
 [0.50500735]]
Shape of r_3: (2, 1)
[[12.72032341  3.72032341]
 [12.50500735  3.50500735]]
Shape of result: (2, 2)


In [10]:
print("r_2:")
print(r_2)
print("Shape of r_2:", r_2.shape)

print("r_4:")
print(r_4)
print("Shape of r_4:", r_4.shape)

result = np.add(r_2, r_4)

print(result)
print("Shape of result:", result.shape)

r_2:
[[15  2]]
Shape of r_2: (1, 2)
r_4:
[[ 89  83  31  83  49]
 [ 54  46  47  39  58]
 [ 93  27  48  77 100]
 [ 56  81  72  63  38]]
Shape of r_4: (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

## Adding r_1 and r_4 gives an error because r_1 has 2 value but r_4 has 5 columns NumPy cannot match the shapes.
## Adding r_2 and r_4 works because r_2 has 1 row and 2 columns.
## Adding r_3 and r_4 gives an error because r_3 has 2 rows and 1 column while r_4 has 4 rows and 5 columns.

In [12]:
print(np.add(np.array([1]), r_4))

[[ 90  84  32  84  50]
 [ 55  47  48  40  59]
 [ 94  28  49  78 101]
 [ 57  82  73  64  39]]


In [13]:
print(np.add(np.array([[1]]), r_4))

[[ 90  84  32  84  50]
 [ 55  47  48  40  59]
 [ 94  28  49  78 101]
 [ 57  82  73  64  39]]


In [14]:
print(np.add(np.array([1, 1, 1, 1, 1]), r_4))

[[ 90  84  32  84  50]
 [ 55  47  48  40  59]
 [ 94  28  49  78 101]
 [ 57  82  73  64  39]]


## an error because np.array([[1], [1]]) has 2 rows and 1 column but r_4 has 4 rows and 5 columns.

# Broadcasting is when NumPy combines arrays with different shapes by using the smaller array to match the bigger array. 
# Using the add function NumPy adds matching positions together. The  final result is usually based on the larger array.

## Rounding

In [15]:
print(r_3)

[[0.72032341]
 [0.50500735]]


In [16]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [17]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [18]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [19]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [20]:
print(np.round(r_3, 2))

[[0.72]
 [0.51]]


## Cumulative Operations

In [21]:
print(r_4)

[[ 89  83  31  83  49]
 [ 54  46  47  39  58]
 [ 93  27  48  77 100]
 [ 56  81  72  63  38]]


In [22]:
print(np.sum(r_4))

1234


In [23]:
print(np.sum(r_4, axis=0))

[292 237 198 262 245]


In [24]:
print(np.sum(r_4, axis=1))

[335 244 345 310]


In [25]:
print(np.cumsum(r_4))

[  89  172  203  286  335  389  435  482  521  579  672  699  747  824
  924  980 1061 1133 1196 1234]


In [26]:
print(np.cumsum(r_4, axis=0))

[[ 89  83  31  83  49]
 [143 129  78 122 107]
 [236 156 126 199 207]
 [292 237 198 262 245]]


## Grocery Problem

In [28]:
# Order: vegetables, fruits, snacks, beverages

bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [29]:
bag1_total = np.sum(bag1)
bag2_total = np.sum(bag2)

print("The first bag contains", bag1_total, "items, and the second bag contains", bag2_total, "items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [30]:
category_totals = np.add(bag1, bag2)

print("There are", category_totals[0], "vegetables,", category_totals[1], "fruits,", category_totals[2], "boxes of snacks, and", category_totals[3], "beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [31]:
ali = np.array([5, 4, 6, 4, 2])
ben = np.array([0, 5, 5, 3, 4])
carla = np.array([3, 6, 0, 3, 4])

In [32]:
all_knocks = np.array([ali, ben, carla])

print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [33]:
person_totals = np.sum(all_knocks, axis=1)
group_total = np.sum(all_knocks)

print("Ali knocked on", person_totals[0], "doors.")
print("Ben knocked on", person_totals[1], "doors.")
print("Carla knocked on", person_totals[2], "doors.")
print("The group knocked on", group_total, "doors total.")

Ali knocked on 21 doors.
Ben knocked on 17 doors.
Carla knocked on 16 doors.
The group knocked on 54 doors total.


In [34]:
daily_totals = np.sum(all_knocks, axis=0)
rolling_total = np.cumsum(daily_totals)
estimated_votes = rolling_total * 0.5

print(estimated_votes)

[ 4.  11.5 17.  22.  27. ]
